### ISSUE TITLE
subscriber agreement error - "WARN lKnownLetsEncryptChallengeEndpointConfig : Please review carefully and accept TOS https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf"

### ISSUE THREAD

**Issue by yarrou** [valb3r/letsencrypt-helper#13]
I'm testing on a server with an already existing certificate from letsencrypt. However, the sample program cannot be run. I am attaching the log. 
``:: Spring Boot ::        (v2.3.4.RELEASE)

2022-07-30 09:25:36.481  INFO 895693 --- [           main] example.SpringBootApp                    : Starting SpringBootApp on **** with PID 895693 (/home/alex/letsencrypt-helper-example-0.1.3-SNAPSHOT.jar started by root in /home/*****)
2022-07-30 09:25:36.490  INFO 895693 --- [           main] example.SpringBootApp                    : No active profile set, falling back to default profiles: default
2022-07-30 09:25:39.248  INFO 895693 --- [           main] lKnownLetsEncryptChallengeEndpointConfig : KeyStore exists: /etc/letsencrypt/live/**************/keystore.p12
2022-07-30 09:25:39.571  INFO 895693 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 443 (https) 80 (http)
2022-07-30 09:25:39.659  INFO 895693 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-07-30 09:25:39.660  INFO 895693 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.38]
2022-07-30 09:25:39.960  INFO 895693 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-07-30 09:25:39.964  INFO 895693 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 3338 ms
2022-07-30 09:25:40.556  WARN 895693 --- [ificate Watcher] lKnownLetsEncryptChallengeEndpointConfig : Please review carefully and accept TOS https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
2022-07-30 09:25:40.608  WARN 895693 --- [ificate Watcher] lKnownLetsEncryptChallengeEndpointConfig : Failed updating KeyStore

java.lang.NullPointerException: null
	at com.github.valb3r.letsencrypthelper.tomcat.TomcatWellKnownLetsEncryptChallengeEndpointConfig.updateCertificateAndKeystore(TomcatWellKnownLetsEncryptChallengeEndpointConfig.java:395) ~[letsencrypt-helper-tomcat-0.2.4.jar!/:na]
	at com.github.valb3r.letsencrypthelper.tomcat.TomcatWellKnownLetsEncryptChallengeEndpointConfig.executeCheckCertValidityAndRotateIfNeeded(TomcatWellKnownLetsEncryptChallengeEndpointConfig.java:336) ~[letsencrypt-helper-tomcat-0.2.4.jar!/:na]
	at com.github.valb3r.letsencrypthelper.tomcat.TomcatWellKnownLetsEncryptChallengeEndpointConfig.letsEncryptCheckCertValidityAndRotateIfNeeded(TomcatWellKnownLetsEncryptChallengeEndpointConfig.java:308) ~[letsencrypt-helper-tomcat-0.2.4.jar!/:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]`
The library and its functionality is what I need. I would love to resolve any issues.

**Comment by valb3r** [comment]
@yarrou It heavily depends on the configuration of the existing KeyStore - the exception you provide indicates that the Keystore is different. This library in general is not aimed on supporting already existing KeyStores out of the box.
Probably this might be seen as enhancement
