### ISSUE TITLE
Latest version 3.0.0 not working with Spring boot 3.1.0, Getting exception

### ISSUE THREAD

**Issue by bishwajitcse** [valb3r/letsencrypt-helper#23]
2023-08-03 12:26:16 [main] [ERROR]    SpringApplication - Application run failed
java.lang.IllegalStateException: Failed to configure LetsEncrypt
	at com.github.valb3r.letsencrypthelper.tomcat.TomcatWellKnownLetsEncryptChallengeEndpointConfig.onApplicationEvent(TomcatWellKnownLetsEncryptChallengeEndpointConfig.java:218)
	at com.github.valb3r.letsencrypthelper.tomcat.TomcatWellKnownLetsEncryptChallengeEndpointConfig.onApplicationEvent(TomcatWellKnownLetsEncryptChallengeEndpointConfig.java:84)
	at com.github.valb3r.letsencrypthelper.tomcat.TomcatWellKnownLetsEncryptChallengeEndpointConfig$$SpringCGLIB$$0.onApplicationEvent(<generated>)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:437)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370)
	at org.springframework.boot.context.event.EventPublishingRunListener.ready(EventPublishingRunListener.java:109)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$ready$6(SpringApplicationRunListeners.java:80)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
	at org.springframework.boot.SpringApplicationRunListeners.ready(SpringApplicationRunListeners.java:80)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1305)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1294)

**Comment by valb3r** [comment]
@bishwajitcse Thanks for the report, it looks like a bug in Spring, since 3.1.0 they use SslConnectorCustomizer and do not call `setCertificateKeystoreFile` anymore, so that SSLHostConfigCertificate points to wrong file. I'll try to create some hacketty hot fix for that

**Comment by bishwajitcse** [comment]
Let me know if you fixed this. I am appreciate to you.  :)

**Comment by valb3r** [comment]
@bishwajitcse You can try 
https://github.com/valb3r/letsencrypt-helper/tree/bugfix/LTH-23-Spring-boot-3.1
it seem to pass tests, but it would require some refactoring before merging. 
You can reference that JAR by using `bugfix~LTH-23-Spring-boot-3.1-SNAPSHOT` version instead of 0.3.0

**Comment by bishwajitcse** [comment]
I will try with this, but it would be good if you merged with master if it works correctly.
Thanks.

**Comment by valb3r** [comment]
@bishwajitcse Merged to master, use `0.4.0` version
