### ISSUE TITLE
It is not working with spring boot 3.3+

### ISSUE THREAD

**Issue by bishwajitcse** [valb3r/letsencrypt-helper#27]
Recently I am upgrading my microservices 3.1+ to 3.3+ after that looking certificate not creating or not renew. Getting this error

Caused by: java.lang.NoSuchFieldError: sphincsPlus_shake_256
	at org.bouncycastle.operator.DefaultSignatureAlgorithmIdentifierFinder.<clinit>(Unknown Source)
	at org.bouncycastle.operator.jcajce.JcaContentSignerBuilder.build(Unknown Source)
	at com.github.valb3r.letsencrypthelper.tomcat.TomcatWellKnownLetsEncryptChallengeEndpointConfig.selfSign(TomcatWellKnownLetsEncryptChallengeEndpointConfig.java:416)
	at com.github.valb3r.letsencrypthelper.tomcat.TomcatWellKnownLetsEncryptChallengeEndpointConfig.createBasicKeystoreWithSelfSignedCert(TomcatWellKnownLetsEncryptChallengeEndpointConfig.java:392)
	at com.github.valb3r.letsencrypthelper.tomcat.TomcatWellKnownLetsEncryptChallengeEndpointConfig.createBasicKeystoreIfMissing(TomcatWellKnownLetsEncryptChallengeEndpointConfig.java:301)
	at com.github.valb3r.letsencrypthelper.tomcat.TomcatWellKnownLetsEncryptChallengeEndpointConfig$CustomTomcatServletWebServerFactoryCustomizer.customize(TomcatWellKnownLetsEncryptChallengeEndpointConfig.java:265)
	at com.github.valb3r.letsencrypthelper.tomcat.TomcatWellKnownLetsEncryptChallengeEndpointConfig$CustomTomcatServletWebServerFactoryCustomizer.customize(TomcatWellKnownLetsEncryptChallengeEndpointConfig.java:252)
	at com.github.valb3r.letsencrypthelper.tomcat.TomcatWellKnownLetsEncryptChallengeEndpointConfig$CustomTomcatServletWebServerFactoryCustomizer$$SpringCGLIB$$0.customize(<generated>)
	at org.springframework.boot.web.server.WebServerFactoryCustomizerBeanPostProcessor.lambda$postProcessBeforeInitialization$0(WebServerFactoryCustomizerBeanPostProcessor.java:72)
	at org.springframework.boot.util.LambdaSafe$Callbacks.lambda$invoke$0(LambdaSafe.java:287)
	at org.springframework.boot.util.LambdaSafe$LambdaSafeCallback.invoke(LambdaSafe.java:159)

**Comment by valb3r** [comment]
@bishwajitcse That's weird, as sphincsPlus_shake_256 is available in BouncyCastle 1.72+ and recent Spring also does seem to work (though it may depend on algorithm list, so not so sure). 
Can you check dependency tree for older BouncyCastle on class path (<1.72)

**Comment by bishwajitcse** [comment]
> @bishwajitcse That's weird, as sphincsPlus_shake_256 is available in BouncyCastle 1.72+ and recent Spring also does seem to work (though it may depend on algorithm list, so not so sure). Can you check dependency tree for older BouncyCastle on class path (<1.72)

Ok. I will check it more. Thanks
